### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by sayertindall** [phra/graphql-apollo-react-chat#28]
I ran the commands in the instructions and am running into this error:

`33 warnings and 15 errors generated.
33 warnings and 15 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp gypERR! build error
 ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR!gyp stack      at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gypERR!  ERR!stack  Error: `make` failed with exit code: 2
stack     at ChildProcess.emit (events.js:210:5)
gypgyp  ERR!ERR!  stackstack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR!gyp  commandERR! \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/sayertindall/Documents/chatTest/chat0/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/sayertindall/Documents/chatTest/chat0/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\"
 Systemgyp Darwin 19.0.0
 ERR! cwdgyp /Users/sayertindall/Documents/chatTest/chat0/node_modules/fsevents
 gypERR!  ERR!command  \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/sayertindall/Documents/chatTest/chat0/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/sayertindall/Documents/chatTest/chat0/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\"
node -v v12.13.1
gypgyp  ERR!ERR!  cwdnode-gyp -v /Users/sayertindall/Documents/chatTest/chat0/node_modules/fsevents
 v5.0.5
gyp gyp ERR!ERR!  node -vnot ok v12.13.1

gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/sayertindall/Documents/chatTest/chat0/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/sayertindall/Documents/chatTest/chat0/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/sayertindall/Documents/chatTest/chat0/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 19.0.0
node-pre-gyp ERR! command \"/usr/local/bin/node\" \"/Users/sayertindall/Documents/chatTest/chat0/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/sayertindall/Documents/chatTest/chat0/node_modules/fsevents
node-pre-gyp ERR! node -v v12.13.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/sayertindall/Documents/chatTest/chat0/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/sayertindall/Documents/chatTest/chat0/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64' (1)"
info This module is OPTIONAL, you can safely ignore this error

$ rimraf docs; graphdoc -s ./schema/schema.gql -o ./docs

[1]
[1] $ node scripts/start.js
[1] internal/modules/cjs/loader.js:800
[1]     throw err;
[1]     ^
[1]
[1] Error: Cannot find module 'webpack'
[1] Require stack:
[1] - /Users/sayertindall/Documents/chatTest/chat0/app/scripts/start.js
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
[1]     at Module.require (internal/modules/cjs/loader.js:852:19)
[1]     at require (internal/modules/cjs/helpers.js:74:18)
[1]     at Object.<anonymous> (/Users/sayertindall/Documents/chatTest/chat0/app/scripts/start.js:19:17)
[1]     at Module._compile (internal/modules/cjs/loader.js:959:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[1]     at Module.load (internal/modules/cjs/loader.js:815:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[1]     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   requireStack: [
[1]     '/Users/sayertindall/Documents/chatTest/chat0/app/scripts/start.js'
[1]   ]
[1] }

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1] cd app && yarn start exited with code 1
--> Sending SIGTERM to other processes..
[0] yarn run docs && ts-node --fast index.ts exited with code null
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by phra** [comment]
no because this codebase is way too old.
